/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancesRouteImport } from './routes/advances'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillBookRouteImport } from './routes/bill-book'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DonationRouteImport } from './routes/donation'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as RaisedActivityRouteImport } from './routes/raised-activity'
import { Route as RaisedVoucherRouteImport } from './routes/raised-voucher'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as UpdateActivityRouteImport } from './routes/update-activity'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'
import { Route as BillBookIndexRouteImport } from './routes/bill-book.index'
import { Route as ChatsGroupIdRouteImport } from './routes/chats.$groupId'
import { Route as ClientsClientNameRouteImport } from './routes/clients.$clientName'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as DonationIndexRouteImport } from './routes/donation.index'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees.$employeeId'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as MaintenanceNewRouteImport } from './routes/maintenance.new'
import { Route as MonitorIndexRouteImport } from './routes/monitor.index'
import { Route as MonitorEmployeeIdRouteImport } from './routes/monitor.$employeeId'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as PayrollEmployeeIdRouteImport } from './routes/payroll.$employeeId'
import { Route as RaisedActivityIndexRouteImport } from './routes/raised-activity.index'
import { Route as RaisedActivityCodeRouteImport } from './routes/raised-activity.$code'
import { Route as RaisedVoucherIndexRouteImport } from './routes/raised-voucher.index'
import { Route as RaisedVoucherVoucherCodeRouteImport } from './routes/raised-voucher.$voucherCode'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions.index'
import { Route as SubmissionsEmployeeIdRouteImport } from './routes/submissions.$employeeId'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as BillBookTypeNewRouteImport } from './routes/bill-book.$type.new'
import { Route as MonitorEmployeeIdIndexRouteImport } from './routes/monitor.$employeeId.index'
import { Route as MonitorEmployeeIdRegularTasksRouteImport } from './routes/monitor.$employeeId.regular-tasks'
import { Route as SubmissionsEmployeeIdIndexRouteImport } from './routes/submissions.$employeeId.index'
import { Route as SubmissionsEmployeeIdTaskIdRouteImport } from './routes/submissions.$employeeId.$taskId'
import { Route as MonitorEmployeeIdRegularTasksIndexRouteImport } from './routes/monitor.$employeeId.regular-tasks.index'
import { Route as MonitorEmployeeIdRegularTasksTaskIdRouteImport } from './routes/monitor.$employeeId.regular-tasks.$taskId'
import { Route as MonitorEmployeeIdVouchersVoucherCodeRouteImport } from './routes/monitor.$employeeId.vouchers.$voucherCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancesRoute = AdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillBookRoute = BillBookRouteImport.update({
  id: '/bill-book',
  path: '/bill-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationRoute = DonationRouteImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const RaisedActivityRoute = RaisedActivityRouteImport.update({
  id: '/raised-activity',
  path: '/raised-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const RaisedVoucherRoute = RaisedVoucherRouteImport.update({
  id: '/raised-voucher',
  path: '/raised-voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateActivityRoute = UpdateActivityRouteImport.update({
  id: '/update-activity',
  path: '/update-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/activities/new',
  path: '/activities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillBookIndexRoute = BillBookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillBookRoute,
} as any)
const ChatsGroupIdRoute = ChatsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => ChatsRoute,
} as any)
const ClientsClientNameRoute = ClientsClientNameRouteImport.update({
  id: '/clients/$clientName',
  path: '/clients/$clientName',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationIndexRoute = DonationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonationRoute,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceNewRoute = MaintenanceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MonitorIndexRoute = MonitorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonitorRoute,
} as any)
const MonitorEmployeeIdRoute = MonitorEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => MonitorRoute,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollEmployeeIdRoute = PayrollEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => PayrollRoute,
} as any)
const RaisedActivityIndexRoute = RaisedActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RaisedActivityRoute,
} as any)
const RaisedActivityCodeRoute = RaisedActivityCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => RaisedActivityRoute,
} as any)
const RaisedVoucherIndexRoute = RaisedVoucherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RaisedVoucherRoute,
} as any)
const RaisedVoucherVoucherCodeRoute =
  RaisedVoucherVoucherCodeRouteImport.update({
    id: '/$voucherCode',
    path: '/$voucherCode',
    getParentRoute: () => RaisedVoucherRoute,
  } as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubmissionsRoute,
} as any)
const SubmissionsEmployeeIdRoute = SubmissionsEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => SubmissionsRoute,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillBookTypeNewRoute = BillBookTypeNewRouteImport.update({
  id: '/$type/new',
  path: '/$type/new',
  getParentRoute: () => BillBookRoute,
} as any)
const MonitorEmployeeIdIndexRoute = MonitorEmployeeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonitorEmployeeIdRoute,
} as any)
const MonitorEmployeeIdRegularTasksRoute =
  MonitorEmployeeIdRegularTasksRouteImport.update({
    id: '/regular-tasks',
    path: '/regular-tasks',
    getParentRoute: () => MonitorEmployeeIdRoute,
  } as any)
const SubmissionsEmployeeIdIndexRoute =
  SubmissionsEmployeeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubmissionsEmployeeIdRoute,
  } as any)
const SubmissionsEmployeeIdTaskIdRoute =
  SubmissionsEmployeeIdTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => SubmissionsEmployeeIdRoute,
  } as any)
const MonitorEmployeeIdRegularTasksIndexRoute =
  MonitorEmployeeIdRegularTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MonitorEmployeeIdRegularTasksRoute,
  } as any)
const MonitorEmployeeIdRegularTasksTaskIdRoute =
  MonitorEmployeeIdRegularTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => MonitorEmployeeIdRegularTasksRoute,
  } as any)
const MonitorEmployeeIdVouchersVoucherCodeRoute =
  MonitorEmployeeIdVouchersVoucherCodeRouteImport.update({
    id: '/vouchers/$voucherCode',
    path: '/vouchers/$voucherCode',
    getParentRoute: () => MonitorEmployeeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advances': typeof AdvancesRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bill-book': typeof BillBookRouteWithChildren
  '/chats': typeof ChatsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/donation': typeof DonationRouteWithChildren
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/monitor': typeof MonitorRouteWithChildren
  '/payroll': typeof PayrollRouteWithChildren
  '/raised-activity': typeof RaisedActivityRouteWithChildren
  '/raised-voucher': typeof RaisedVoucherRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/update-activity': typeof UpdateActivityRoute
  '/vault': typeof VaultRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/chats/$groupId': typeof ChatsGroupIdRoute
  '/clients/$clientName': typeof ClientsClientNameRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/maintenance/new': typeof MaintenanceNewRoute
  '/monitor/$employeeId': typeof MonitorEmployeeIdRouteWithChildren
  '/payroll/$employeeId': typeof PayrollEmployeeIdRoute
  '/raised-activity/$code': typeof RaisedActivityCodeRoute
  '/raised-voucher/$voucherCode': typeof RaisedVoucherVoucherCodeRoute
  '/submissions/$employeeId': typeof SubmissionsEmployeeIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/bill-book/': typeof BillBookIndexRoute
  '/donation/': typeof DonationIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/raised-activity/': typeof RaisedActivityIndexRoute
  '/raised-voucher/': typeof RaisedVoucherIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/bill-book/$type/new': typeof BillBookTypeNewRoute
  '/monitor/$employeeId/regular-tasks': typeof MonitorEmployeeIdRegularTasksRouteWithChildren
  '/submissions/$employeeId/$taskId': typeof SubmissionsEmployeeIdTaskIdRoute
  '/monitor/$employeeId/': typeof MonitorEmployeeIdIndexRoute
  '/submissions/$employeeId/': typeof SubmissionsEmployeeIdIndexRoute
  '/monitor/$employeeId/regular-tasks/$taskId': typeof MonitorEmployeeIdRegularTasksTaskIdRoute
  '/monitor/$employeeId/vouchers/$voucherCode': typeof MonitorEmployeeIdVouchersVoucherCodeRoute
  '/monitor/$employeeId/regular-tasks/': typeof MonitorEmployeeIdRegularTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advances': typeof AdvancesRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/update-activity': typeof UpdateActivityRoute
  '/vault': typeof VaultRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/chats/$groupId': typeof ChatsGroupIdRoute
  '/clients/$clientName': typeof ClientsClientNameRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/maintenance/new': typeof MaintenanceNewRoute
  '/payroll/$employeeId': typeof PayrollEmployeeIdRoute
  '/raised-activity/$code': typeof RaisedActivityCodeRoute
  '/raised-voucher/$voucherCode': typeof RaisedVoucherVoucherCodeRoute
  '/tasks/new': typeof TasksNewRoute
  '/bill-book': typeof BillBookIndexRoute
  '/donation': typeof DonationIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/monitor': typeof MonitorIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/raised-activity': typeof RaisedActivityIndexRoute
  '/raised-voucher': typeof RaisedVoucherIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/bill-book/$type/new': typeof BillBookTypeNewRoute
  '/submissions/$employeeId/$taskId': typeof SubmissionsEmployeeIdTaskIdRoute
  '/monitor/$employeeId': typeof MonitorEmployeeIdIndexRoute
  '/submissions/$employeeId': typeof SubmissionsEmployeeIdIndexRoute
  '/monitor/$employeeId/regular-tasks/$taskId': typeof MonitorEmployeeIdRegularTasksTaskIdRoute
  '/monitor/$employeeId/vouchers/$voucherCode': typeof MonitorEmployeeIdVouchersVoucherCodeRoute
  '/monitor/$employeeId/regular-tasks': typeof MonitorEmployeeIdRegularTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advances': typeof AdvancesRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bill-book': typeof BillBookRouteWithChildren
  '/chats': typeof ChatsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/donation': typeof DonationRouteWithChildren
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/monitor': typeof MonitorRouteWithChildren
  '/payroll': typeof PayrollRouteWithChildren
  '/raised-activity': typeof RaisedActivityRouteWithChildren
  '/raised-voucher': typeof RaisedVoucherRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/update-activity': typeof UpdateActivityRoute
  '/vault': typeof VaultRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/chats/$groupId': typeof ChatsGroupIdRoute
  '/clients/$clientName': typeof ClientsClientNameRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/maintenance/new': typeof MaintenanceNewRoute
  '/monitor/$employeeId': typeof MonitorEmployeeIdRouteWithChildren
  '/payroll/$employeeId': typeof PayrollEmployeeIdRoute
  '/raised-activity/$code': typeof RaisedActivityCodeRoute
  '/raised-voucher/$voucherCode': typeof RaisedVoucherVoucherCodeRoute
  '/submissions/$employeeId': typeof SubmissionsEmployeeIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/bill-book/': typeof BillBookIndexRoute
  '/donation/': typeof DonationIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/monitor/': typeof MonitorIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/raised-activity/': typeof RaisedActivityIndexRoute
  '/raised-voucher/': typeof RaisedVoucherIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/bill-book/$type/new': typeof BillBookTypeNewRoute
  '/monitor/$employeeId/regular-tasks': typeof MonitorEmployeeIdRegularTasksRouteWithChildren
  '/submissions/$employeeId/$taskId': typeof SubmissionsEmployeeIdTaskIdRoute
  '/monitor/$employeeId/': typeof MonitorEmployeeIdIndexRoute
  '/submissions/$employeeId/': typeof SubmissionsEmployeeIdIndexRoute
  '/monitor/$employeeId/regular-tasks/$taskId': typeof MonitorEmployeeIdRegularTasksTaskIdRoute
  '/monitor/$employeeId/vouchers/$voucherCode': typeof MonitorEmployeeIdVouchersVoucherCodeRoute
  '/monitor/$employeeId/regular-tasks/': typeof MonitorEmployeeIdRegularTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advances'
    | '/analytics'
    | '/auth'
    | '/bill-book'
    | '/chats'
    | '/dashboard'
    | '/donation'
    | '/help'
    | '/maintenance'
    | '/monitor'
    | '/payroll'
    | '/raised-activity'
    | '/raised-voucher'
    | '/settings'
    | '/submissions'
    | '/update-activity'
    | '/vault'
    | '/activities/new'
    | '/chats/$groupId'
    | '/clients/$clientName'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/maintenance/new'
    | '/monitor/$employeeId'
    | '/payroll/$employeeId'
    | '/raised-activity/$code'
    | '/raised-voucher/$voucherCode'
    | '/submissions/$employeeId'
    | '/tasks/new'
    | '/bill-book/'
    | '/donation/'
    | '/maintenance/'
    | '/monitor/'
    | '/payroll/'
    | '/raised-activity/'
    | '/raised-voucher/'
    | '/submissions/'
    | '/bill-book/$type/new'
    | '/monitor/$employeeId/regular-tasks'
    | '/submissions/$employeeId/$taskId'
    | '/monitor/$employeeId/'
    | '/submissions/$employeeId/'
    | '/monitor/$employeeId/regular-tasks/$taskId'
    | '/monitor/$employeeId/vouchers/$voucherCode'
    | '/monitor/$employeeId/regular-tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advances'
    | '/analytics'
    | '/auth'
    | '/chats'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/update-activity'
    | '/vault'
    | '/activities/new'
    | '/chats/$groupId'
    | '/clients/$clientName'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/maintenance/new'
    | '/payroll/$employeeId'
    | '/raised-activity/$code'
    | '/raised-voucher/$voucherCode'
    | '/tasks/new'
    | '/bill-book'
    | '/donation'
    | '/maintenance'
    | '/monitor'
    | '/payroll'
    | '/raised-activity'
    | '/raised-voucher'
    | '/submissions'
    | '/bill-book/$type/new'
    | '/submissions/$employeeId/$taskId'
    | '/monitor/$employeeId'
    | '/submissions/$employeeId'
    | '/monitor/$employeeId/regular-tasks/$taskId'
    | '/monitor/$employeeId/vouchers/$voucherCode'
    | '/monitor/$employeeId/regular-tasks'
  id:
    | '__root__'
    | '/'
    | '/advances'
    | '/analytics'
    | '/auth'
    | '/bill-book'
    | '/chats'
    | '/dashboard'
    | '/donation'
    | '/help'
    | '/maintenance'
    | '/monitor'
    | '/payroll'
    | '/raised-activity'
    | '/raised-voucher'
    | '/settings'
    | '/submissions'
    | '/update-activity'
    | '/vault'
    | '/activities/new'
    | '/chats/$groupId'
    | '/clients/$clientName'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/maintenance/new'
    | '/monitor/$employeeId'
    | '/payroll/$employeeId'
    | '/raised-activity/$code'
    | '/raised-voucher/$voucherCode'
    | '/submissions/$employeeId'
    | '/tasks/new'
    | '/bill-book/'
    | '/donation/'
    | '/maintenance/'
    | '/monitor/'
    | '/payroll/'
    | '/raised-activity/'
    | '/raised-voucher/'
    | '/submissions/'
    | '/bill-book/$type/new'
    | '/monitor/$employeeId/regular-tasks'
    | '/submissions/$employeeId/$taskId'
    | '/monitor/$employeeId/'
    | '/submissions/$employeeId/'
    | '/monitor/$employeeId/regular-tasks/$taskId'
    | '/monitor/$employeeId/vouchers/$voucherCode'
    | '/monitor/$employeeId/regular-tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancesRoute: typeof AdvancesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BillBookRoute: typeof BillBookRouteWithChildren
  ChatsRoute: typeof ChatsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DonationRoute: typeof DonationRouteWithChildren
  HelpRoute: typeof HelpRoute
  MaintenanceRoute: typeof MaintenanceRouteWithChildren
  MonitorRoute: typeof MonitorRouteWithChildren
  PayrollRoute: typeof PayrollRouteWithChildren
  RaisedActivityRoute: typeof RaisedActivityRouteWithChildren
  RaisedVoucherRoute: typeof RaisedVoucherRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubmissionsRoute: typeof SubmissionsRouteWithChildren
  UpdateActivityRoute: typeof UpdateActivityRoute
  VaultRoute: typeof VaultRoute
  ActivitiesNewRoute: typeof ActivitiesNewRoute
  ClientsClientNameRoute: typeof ClientsClientNameRoute
  ClientsNewRoute: typeof ClientsNewRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  TasksNewRoute: typeof TasksNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advances': {
      id: '/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AdvancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-book': {
      id: '/bill-book'
      path: '/bill-book'
      fullPath: '/bill-book'
      preLoaderRoute: typeof BillBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation': {
      id: '/donation'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof DonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raised-activity': {
      id: '/raised-activity'
      path: '/raised-activity'
      fullPath: '/raised-activity'
      preLoaderRoute: typeof RaisedActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raised-voucher': {
      id: '/raised-voucher'
      path: '/raised-voucher'
      fullPath: '/raised-voucher'
      preLoaderRoute: typeof RaisedVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-activity': {
      id: '/update-activity'
      path: '/update-activity'
      fullPath: '/update-activity'
      preLoaderRoute: typeof UpdateActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/activities/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-book/': {
      id: '/bill-book/'
      path: '/'
      fullPath: '/bill-book/'
      preLoaderRoute: typeof BillBookIndexRouteImport
      parentRoute: typeof BillBookRoute
    }
    '/chats/$groupId': {
      id: '/chats/$groupId'
      path: '/$groupId'
      fullPath: '/chats/$groupId'
      preLoaderRoute: typeof ChatsGroupIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/clients/$clientName': {
      id: '/clients/$clientName'
      path: '/clients/$clientName'
      fullPath: '/clients/$clientName'
      preLoaderRoute: typeof ClientsClientNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation/': {
      id: '/donation/'
      path: '/'
      fullPath: '/donation/'
      preLoaderRoute: typeof DonationIndexRouteImport
      parentRoute: typeof DonationRoute
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/new': {
      id: '/maintenance/new'
      path: '/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof MaintenanceNewRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/monitor/': {
      id: '/monitor/'
      path: '/'
      fullPath: '/monitor/'
      preLoaderRoute: typeof MonitorIndexRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/monitor/$employeeId': {
      id: '/monitor/$employeeId'
      path: '/$employeeId'
      fullPath: '/monitor/$employeeId'
      preLoaderRoute: typeof MonitorEmployeeIdRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/$employeeId': {
      id: '/payroll/$employeeId'
      path: '/$employeeId'
      fullPath: '/payroll/$employeeId'
      preLoaderRoute: typeof PayrollEmployeeIdRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/raised-activity/': {
      id: '/raised-activity/'
      path: '/'
      fullPath: '/raised-activity/'
      preLoaderRoute: typeof RaisedActivityIndexRouteImport
      parentRoute: typeof RaisedActivityRoute
    }
    '/raised-activity/$code': {
      id: '/raised-activity/$code'
      path: '/$code'
      fullPath: '/raised-activity/$code'
      preLoaderRoute: typeof RaisedActivityCodeRouteImport
      parentRoute: typeof RaisedActivityRoute
    }
    '/raised-voucher/': {
      id: '/raised-voucher/'
      path: '/'
      fullPath: '/raised-voucher/'
      preLoaderRoute: typeof RaisedVoucherIndexRouteImport
      parentRoute: typeof RaisedVoucherRoute
    }
    '/raised-voucher/$voucherCode': {
      id: '/raised-voucher/$voucherCode'
      path: '/$voucherCode'
      fullPath: '/raised-voucher/$voucherCode'
      preLoaderRoute: typeof RaisedVoucherVoucherCodeRouteImport
      parentRoute: typeof RaisedVoucherRoute
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/submissions/$employeeId': {
      id: '/submissions/$employeeId'
      path: '/$employeeId'
      fullPath: '/submissions/$employeeId'
      preLoaderRoute: typeof SubmissionsEmployeeIdRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-book/$type/new': {
      id: '/bill-book/$type/new'
      path: '/$type/new'
      fullPath: '/bill-book/$type/new'
      preLoaderRoute: typeof BillBookTypeNewRouteImport
      parentRoute: typeof BillBookRoute
    }
    '/monitor/$employeeId/': {
      id: '/monitor/$employeeId/'
      path: '/'
      fullPath: '/monitor/$employeeId/'
      preLoaderRoute: typeof MonitorEmployeeIdIndexRouteImport
      parentRoute: typeof MonitorEmployeeIdRoute
    }
    '/monitor/$employeeId/regular-tasks': {
      id: '/monitor/$employeeId/regular-tasks'
      path: '/regular-tasks'
      fullPath: '/monitor/$employeeId/regular-tasks'
      preLoaderRoute: typeof MonitorEmployeeIdRegularTasksRouteImport
      parentRoute: typeof MonitorEmployeeIdRoute
    }
    '/submissions/$employeeId/': {
      id: '/submissions/$employeeId/'
      path: '/'
      fullPath: '/submissions/$employeeId/'
      preLoaderRoute: typeof SubmissionsEmployeeIdIndexRouteImport
      parentRoute: typeof SubmissionsEmployeeIdRoute
    }
    '/submissions/$employeeId/$taskId': {
      id: '/submissions/$employeeId/$taskId'
      path: '/$taskId'
      fullPath: '/submissions/$employeeId/$taskId'
      preLoaderRoute: typeof SubmissionsEmployeeIdTaskIdRouteImport
      parentRoute: typeof SubmissionsEmployeeIdRoute
    }
    '/monitor/$employeeId/regular-tasks/': {
      id: '/monitor/$employeeId/regular-tasks/'
      path: '/'
      fullPath: '/monitor/$employeeId/regular-tasks/'
      preLoaderRoute: typeof MonitorEmployeeIdRegularTasksIndexRouteImport
      parentRoute: typeof MonitorEmployeeIdRegularTasksRoute
    }
    '/monitor/$employeeId/regular-tasks/$taskId': {
      id: '/monitor/$employeeId/regular-tasks/$taskId'
      path: '/$taskId'
      fullPath: '/monitor/$employeeId/regular-tasks/$taskId'
      preLoaderRoute: typeof MonitorEmployeeIdRegularTasksTaskIdRouteImport
      parentRoute: typeof MonitorEmployeeIdRegularTasksRoute
    }
    '/monitor/$employeeId/vouchers/$voucherCode': {
      id: '/monitor/$employeeId/vouchers/$voucherCode'
      path: '/vouchers/$voucherCode'
      fullPath: '/monitor/$employeeId/vouchers/$voucherCode'
      preLoaderRoute: typeof MonitorEmployeeIdVouchersVoucherCodeRouteImport
      parentRoute: typeof MonitorEmployeeIdRoute
    }
  }
}

interface BillBookRouteChildren {
  BillBookIndexRoute: typeof BillBookIndexRoute
  BillBookTypeNewRoute: typeof BillBookTypeNewRoute
}

const BillBookRouteChildren: BillBookRouteChildren = {
  BillBookIndexRoute: BillBookIndexRoute,
  BillBookTypeNewRoute: BillBookTypeNewRoute,
}

const BillBookRouteWithChildren = BillBookRoute._addFileChildren(
  BillBookRouteChildren,
)

interface ChatsRouteChildren {
  ChatsGroupIdRoute: typeof ChatsGroupIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsGroupIdRoute: ChatsGroupIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface DonationRouteChildren {
  DonationIndexRoute: typeof DonationIndexRoute
}

const DonationRouteChildren: DonationRouteChildren = {
  DonationIndexRoute: DonationIndexRoute,
}

const DonationRouteWithChildren = DonationRoute._addFileChildren(
  DonationRouteChildren,
)

interface MaintenanceRouteChildren {
  MaintenanceNewRoute: typeof MaintenanceNewRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
}

const MaintenanceRouteChildren: MaintenanceRouteChildren = {
  MaintenanceNewRoute: MaintenanceNewRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
}

const MaintenanceRouteWithChildren = MaintenanceRoute._addFileChildren(
  MaintenanceRouteChildren,
)

interface MonitorEmployeeIdRegularTasksRouteChildren {
  MonitorEmployeeIdRegularTasksTaskIdRoute: typeof MonitorEmployeeIdRegularTasksTaskIdRoute
  MonitorEmployeeIdRegularTasksIndexRoute: typeof MonitorEmployeeIdRegularTasksIndexRoute
}

const MonitorEmployeeIdRegularTasksRouteChildren: MonitorEmployeeIdRegularTasksRouteChildren =
  {
    MonitorEmployeeIdRegularTasksTaskIdRoute:
      MonitorEmployeeIdRegularTasksTaskIdRoute,
    MonitorEmployeeIdRegularTasksIndexRoute:
      MonitorEmployeeIdRegularTasksIndexRoute,
  }

const MonitorEmployeeIdRegularTasksRouteWithChildren =
  MonitorEmployeeIdRegularTasksRoute._addFileChildren(
    MonitorEmployeeIdRegularTasksRouteChildren,
  )

interface MonitorEmployeeIdRouteChildren {
  MonitorEmployeeIdRegularTasksRoute: typeof MonitorEmployeeIdRegularTasksRouteWithChildren
  MonitorEmployeeIdIndexRoute: typeof MonitorEmployeeIdIndexRoute
  MonitorEmployeeIdVouchersVoucherCodeRoute: typeof MonitorEmployeeIdVouchersVoucherCodeRoute
}

const MonitorEmployeeIdRouteChildren: MonitorEmployeeIdRouteChildren = {
  MonitorEmployeeIdRegularTasksRoute:
    MonitorEmployeeIdRegularTasksRouteWithChildren,
  MonitorEmployeeIdIndexRoute: MonitorEmployeeIdIndexRoute,
  MonitorEmployeeIdVouchersVoucherCodeRoute:
    MonitorEmployeeIdVouchersVoucherCodeRoute,
}

const MonitorEmployeeIdRouteWithChildren =
  MonitorEmployeeIdRoute._addFileChildren(MonitorEmployeeIdRouteChildren)

interface MonitorRouteChildren {
  MonitorEmployeeIdRoute: typeof MonitorEmployeeIdRouteWithChildren
  MonitorIndexRoute: typeof MonitorIndexRoute
}

const MonitorRouteChildren: MonitorRouteChildren = {
  MonitorEmployeeIdRoute: MonitorEmployeeIdRouteWithChildren,
  MonitorIndexRoute: MonitorIndexRoute,
}

const MonitorRouteWithChildren =
  MonitorRoute._addFileChildren(MonitorRouteChildren)

interface PayrollRouteChildren {
  PayrollEmployeeIdRoute: typeof PayrollEmployeeIdRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollEmployeeIdRoute: PayrollEmployeeIdRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

interface RaisedActivityRouteChildren {
  RaisedActivityCodeRoute: typeof RaisedActivityCodeRoute
  RaisedActivityIndexRoute: typeof RaisedActivityIndexRoute
}

const RaisedActivityRouteChildren: RaisedActivityRouteChildren = {
  RaisedActivityCodeRoute: RaisedActivityCodeRoute,
  RaisedActivityIndexRoute: RaisedActivityIndexRoute,
}

const RaisedActivityRouteWithChildren = RaisedActivityRoute._addFileChildren(
  RaisedActivityRouteChildren,
)

interface RaisedVoucherRouteChildren {
  RaisedVoucherVoucherCodeRoute: typeof RaisedVoucherVoucherCodeRoute
  RaisedVoucherIndexRoute: typeof RaisedVoucherIndexRoute
}

const RaisedVoucherRouteChildren: RaisedVoucherRouteChildren = {
  RaisedVoucherVoucherCodeRoute: RaisedVoucherVoucherCodeRoute,
  RaisedVoucherIndexRoute: RaisedVoucherIndexRoute,
}

const RaisedVoucherRouteWithChildren = RaisedVoucherRoute._addFileChildren(
  RaisedVoucherRouteChildren,
)

interface SubmissionsEmployeeIdRouteChildren {
  SubmissionsEmployeeIdTaskIdRoute: typeof SubmissionsEmployeeIdTaskIdRoute
  SubmissionsEmployeeIdIndexRoute: typeof SubmissionsEmployeeIdIndexRoute
}

const SubmissionsEmployeeIdRouteChildren: SubmissionsEmployeeIdRouteChildren = {
  SubmissionsEmployeeIdTaskIdRoute: SubmissionsEmployeeIdTaskIdRoute,
  SubmissionsEmployeeIdIndexRoute: SubmissionsEmployeeIdIndexRoute,
}

const SubmissionsEmployeeIdRouteWithChildren =
  SubmissionsEmployeeIdRoute._addFileChildren(
    SubmissionsEmployeeIdRouteChildren,
  )

interface SubmissionsRouteChildren {
  SubmissionsEmployeeIdRoute: typeof SubmissionsEmployeeIdRouteWithChildren
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

const SubmissionsRouteChildren: SubmissionsRouteChildren = {
  SubmissionsEmployeeIdRoute: SubmissionsEmployeeIdRouteWithChildren,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}

const SubmissionsRouteWithChildren = SubmissionsRoute._addFileChildren(
  SubmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancesRoute: AdvancesRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BillBookRoute: BillBookRouteWithChildren,
  ChatsRoute: ChatsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DonationRoute: DonationRouteWithChildren,
  HelpRoute: HelpRoute,
  MaintenanceRoute: MaintenanceRouteWithChildren,
  MonitorRoute: MonitorRouteWithChildren,
  PayrollRoute: PayrollRouteWithChildren,
  RaisedActivityRoute: RaisedActivityRouteWithChildren,
  RaisedVoucherRoute: RaisedVoucherRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubmissionsRoute: SubmissionsRouteWithChildren,
  UpdateActivityRoute: UpdateActivityRoute,
  VaultRoute: VaultRoute,
  ActivitiesNewRoute: ActivitiesNewRoute,
  ClientsClientNameRoute: ClientsClientNameRoute,
  ClientsNewRoute: ClientsNewRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  TasksNewRoute: TasksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
