/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancesRouteImport } from './routes/advances'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillBookRouteImport } from './routes/bill-book'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees.$employeeId'
import { Route as EmployeesNewRouteImport } from './routes/employees.new'
import { Route as MonitorIndexRouteImport } from './routes/monitor.index'
import { Route as MonitorEmployeeIdRouteImport } from './routes/monitor.$employeeId'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as PayrollEmployeeIdRouteImport } from './routes/payroll.$employeeId'
import { Route as SubmissionsIndexRouteImport } from './routes/submissions.index'
import { Route as SubmissionsEmployeeIdRouteImport } from './routes/submissions.$employeeId'
import { Route as TasksNewRouteImport } from './routes/tasks.new'
import { Route as SubmissionsEmployeeIdIndexRouteImport } from './routes/submissions.$employeeId.index'
import { Route as SubmissionsEmployeeIdTaskIdRouteImport } from './routes/submissions.$employeeId.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancesRoute = AdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillBookRoute = BillBookRouteImport.update({
  id: '/bill-book',
  path: '/bill-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/activities/new',
  path: '/activities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIndexRoute = MonitorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonitorRoute,
} as any)
const MonitorEmployeeIdRoute = MonitorEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => MonitorRoute,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollEmployeeIdRoute = PayrollEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => PayrollRoute,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubmissionsRoute,
} as any)
const SubmissionsEmployeeIdRoute = SubmissionsEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => SubmissionsRoute,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsEmployeeIdIndexRoute =
  SubmissionsEmployeeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubmissionsEmployeeIdRoute,
  } as any)
const SubmissionsEmployeeIdTaskIdRoute =
  SubmissionsEmployeeIdTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => SubmissionsEmployeeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advances': typeof AdvancesRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bill-book': typeof BillBookRoute
  '/chats': typeof ChatsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/payroll': typeof PayrollRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/vault': typeof VaultRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/monitor/$employeeId': typeof MonitorEmployeeIdRoute
  '/payroll/$employeeId': typeof PayrollEmployeeIdRoute
  '/submissions/$employeeId': typeof SubmissionsEmployeeIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/monitor/': typeof MonitorIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/submissions/$employeeId/$taskId': typeof SubmissionsEmployeeIdTaskIdRoute
  '/submissions/$employeeId/': typeof SubmissionsEmployeeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advances': typeof AdvancesRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bill-book': typeof BillBookRoute
  '/chats': typeof ChatsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/settings': typeof SettingsRoute
  '/vault': typeof VaultRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/monitor/$employeeId': typeof MonitorEmployeeIdRoute
  '/payroll/$employeeId': typeof PayrollEmployeeIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/monitor': typeof MonitorIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/submissions': typeof SubmissionsIndexRoute
  '/submissions/$employeeId/$taskId': typeof SubmissionsEmployeeIdTaskIdRoute
  '/submissions/$employeeId': typeof SubmissionsEmployeeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advances': typeof AdvancesRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/bill-book': typeof BillBookRoute
  '/chats': typeof ChatsRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/monitor': typeof MonitorRouteWithChildren
  '/payroll': typeof PayrollRouteWithChildren
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRouteWithChildren
  '/vault': typeof VaultRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/clients/new': typeof ClientsNewRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/new': typeof EmployeesNewRoute
  '/monitor/$employeeId': typeof MonitorEmployeeIdRoute
  '/payroll/$employeeId': typeof PayrollEmployeeIdRoute
  '/submissions/$employeeId': typeof SubmissionsEmployeeIdRouteWithChildren
  '/tasks/new': typeof TasksNewRoute
  '/monitor/': typeof MonitorIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/submissions/': typeof SubmissionsIndexRoute
  '/submissions/$employeeId/$taskId': typeof SubmissionsEmployeeIdTaskIdRoute
  '/submissions/$employeeId/': typeof SubmissionsEmployeeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advances'
    | '/analytics'
    | '/auth'
    | '/bill-book'
    | '/chats'
    | '/dashboard'
    | '/help'
    | '/monitor'
    | '/payroll'
    | '/settings'
    | '/submissions'
    | '/vault'
    | '/activities/new'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/monitor/$employeeId'
    | '/payroll/$employeeId'
    | '/submissions/$employeeId'
    | '/tasks/new'
    | '/monitor/'
    | '/payroll/'
    | '/submissions/'
    | '/submissions/$employeeId/$taskId'
    | '/submissions/$employeeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advances'
    | '/analytics'
    | '/auth'
    | '/bill-book'
    | '/chats'
    | '/dashboard'
    | '/help'
    | '/settings'
    | '/vault'
    | '/activities/new'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/monitor/$employeeId'
    | '/payroll/$employeeId'
    | '/tasks/new'
    | '/monitor'
    | '/payroll'
    | '/submissions'
    | '/submissions/$employeeId/$taskId'
    | '/submissions/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/advances'
    | '/analytics'
    | '/auth'
    | '/bill-book'
    | '/chats'
    | '/dashboard'
    | '/help'
    | '/monitor'
    | '/payroll'
    | '/settings'
    | '/submissions'
    | '/vault'
    | '/activities/new'
    | '/clients/new'
    | '/employees/$employeeId'
    | '/employees/new'
    | '/monitor/$employeeId'
    | '/payroll/$employeeId'
    | '/submissions/$employeeId'
    | '/tasks/new'
    | '/monitor/'
    | '/payroll/'
    | '/submissions/'
    | '/submissions/$employeeId/$taskId'
    | '/submissions/$employeeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancesRoute: typeof AdvancesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BillBookRoute: typeof BillBookRoute
  ChatsRoute: typeof ChatsRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  MonitorRoute: typeof MonitorRouteWithChildren
  PayrollRoute: typeof PayrollRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubmissionsRoute: typeof SubmissionsRouteWithChildren
  VaultRoute: typeof VaultRoute
  ActivitiesNewRoute: typeof ActivitiesNewRoute
  ClientsNewRoute: typeof ClientsNewRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  TasksNewRoute: typeof TasksNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advances': {
      id: '/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AdvancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-book': {
      id: '/bill-book'
      path: '/bill-book'
      fullPath: '/bill-book'
      preLoaderRoute: typeof BillBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/activities/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/new': {
      id: '/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/': {
      id: '/monitor/'
      path: '/'
      fullPath: '/monitor/'
      preLoaderRoute: typeof MonitorIndexRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/monitor/$employeeId': {
      id: '/monitor/$employeeId'
      path: '/$employeeId'
      fullPath: '/monitor/$employeeId'
      preLoaderRoute: typeof MonitorEmployeeIdRouteImport
      parentRoute: typeof MonitorRoute
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/$employeeId': {
      id: '/payroll/$employeeId'
      path: '/$employeeId'
      fullPath: '/payroll/$employeeId'
      preLoaderRoute: typeof PayrollEmployeeIdRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/submissions/': {
      id: '/submissions/'
      path: '/'
      fullPath: '/submissions/'
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/submissions/$employeeId': {
      id: '/submissions/$employeeId'
      path: '/$employeeId'
      fullPath: '/submissions/$employeeId'
      preLoaderRoute: typeof SubmissionsEmployeeIdRouteImport
      parentRoute: typeof SubmissionsRoute
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$employeeId/': {
      id: '/submissions/$employeeId/'
      path: '/'
      fullPath: '/submissions/$employeeId/'
      preLoaderRoute: typeof SubmissionsEmployeeIdIndexRouteImport
      parentRoute: typeof SubmissionsEmployeeIdRoute
    }
    '/submissions/$employeeId/$taskId': {
      id: '/submissions/$employeeId/$taskId'
      path: '/$taskId'
      fullPath: '/submissions/$employeeId/$taskId'
      preLoaderRoute: typeof SubmissionsEmployeeIdTaskIdRouteImport
      parentRoute: typeof SubmissionsEmployeeIdRoute
    }
  }
}

interface MonitorRouteChildren {
  MonitorEmployeeIdRoute: typeof MonitorEmployeeIdRoute
  MonitorIndexRoute: typeof MonitorIndexRoute
}

const MonitorRouteChildren: MonitorRouteChildren = {
  MonitorEmployeeIdRoute: MonitorEmployeeIdRoute,
  MonitorIndexRoute: MonitorIndexRoute,
}

const MonitorRouteWithChildren =
  MonitorRoute._addFileChildren(MonitorRouteChildren)

interface PayrollRouteChildren {
  PayrollEmployeeIdRoute: typeof PayrollEmployeeIdRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollEmployeeIdRoute: PayrollEmployeeIdRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

interface SubmissionsEmployeeIdRouteChildren {
  SubmissionsEmployeeIdTaskIdRoute: typeof SubmissionsEmployeeIdTaskIdRoute
  SubmissionsEmployeeIdIndexRoute: typeof SubmissionsEmployeeIdIndexRoute
}

const SubmissionsEmployeeIdRouteChildren: SubmissionsEmployeeIdRouteChildren = {
  SubmissionsEmployeeIdTaskIdRoute: SubmissionsEmployeeIdTaskIdRoute,
  SubmissionsEmployeeIdIndexRoute: SubmissionsEmployeeIdIndexRoute,
}

const SubmissionsEmployeeIdRouteWithChildren =
  SubmissionsEmployeeIdRoute._addFileChildren(
    SubmissionsEmployeeIdRouteChildren,
  )

interface SubmissionsRouteChildren {
  SubmissionsEmployeeIdRoute: typeof SubmissionsEmployeeIdRouteWithChildren
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

const SubmissionsRouteChildren: SubmissionsRouteChildren = {
  SubmissionsEmployeeIdRoute: SubmissionsEmployeeIdRouteWithChildren,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}

const SubmissionsRouteWithChildren = SubmissionsRoute._addFileChildren(
  SubmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancesRoute: AdvancesRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BillBookRoute: BillBookRoute,
  ChatsRoute: ChatsRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  MonitorRoute: MonitorRouteWithChildren,
  PayrollRoute: PayrollRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubmissionsRoute: SubmissionsRouteWithChildren,
  VaultRoute: VaultRoute,
  ActivitiesNewRoute: ActivitiesNewRoute,
  ClientsNewRoute: ClientsNewRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  TasksNewRoute: TasksNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
